[context.branch-deploy]
command = """
npm run build && echo -e "/*
  Basic-Auth: ${PREVIEW_LOGIN}:${PREVIEW_PASSWORD}" > _site/_headers"""

[context.deploy-preview]
command = """
npm run build && echo -e "/*
  Basic-Auth: ${PREVIEW_LOGIN}:${PREVIEW_PASSWORD}" > _site/_headers"""

[[plugins]]
package = "netlify-plugin-inline-functions-env"
