[context.branch-deploy]
command = """
npm run build && echo -e "/*
  Basic-Auth: ${PREVIEW_LOGIN}:${PREVIEW_PASSWORD}" > _site/_headers"""

[context.deploy-preview]
command = """
npm run build && echo -e "/*
  Basic-Auth: ${PREVIEW_LOGIN}:${PREVIEW_PASSWORD}" > _site/_headers"""

[[plugins]]
package = "netlify-plugin-inline-functions-env"

  [plugins.inputs]
  include = [ "CONTEXT", "URL" ]

[[redirects]]
from = "undefined"
to = "/.netlify/functions/secure"
status = 200
force = true
_generated_by_eleventy_serverless = "secure"

[[redirects]]
from = "/"
to = "/.netlify/functions/secure"
status = 200
force = true
_generated_by_eleventy_serverless = "secure"
