[context.branch-deploy]
command = """
echo $PREVIEW_LOGIN && npm run build && echo -e "/*
  Basic-Auth: ${PREVIEW_LOGIN}:${PREVIEW_PASSWORD}" > _site/_headers"""

  [context.branch-deploy.environment]
  IS_PREVIEW = "true"

[context.deploy-preview]
command = """
echo $PREVIEW_LOGIN && npm run build && echo -e "/*
  Basic-Auth: ${PREVIEW_LOGIN}:${PREVIEW_PASSWORD}" > _site/_headers"""

  [context.deploy-preview.environment]
  IS_PREVIEW = "true"
