[build]
command = "npm run build && echo $CONTEXT > .env"

[context.branch-deploy]
command = """
npm run build && echo $CONTEXT >> .env && echo -e "/*
  Basic-Auth: ${PREVIEW_LOGIN}:${PREVIEW_PASSWORD}" > _site/_headers"""

[context.deploy-preview]
command = """
npm run build && echo $CONTEXT >> .env && echo -e "/*
  Basic-Auth: ${PREVIEW_LOGIN}:${PREVIEW_PASSWORD}" > _site/_headers"""
