[context.branch-deploy]
command = """
npx @11ty/eleventy && echo -e '*/
  Basic-Auth: $PREVIEW_LOGIN:$PREVIEW_PASSWORD' > _site/_headers"""

[context.deploy-preview]
command = """
npx @11ty/eleventy && echo -e '*/
  Basic-Auth: $PREVIEW_LOGIN:$PREVIEW_PASSWORD' > _site/_headers"""

[context.deploy-preview.environment]
NODE_ENV = "preview"

[context.branch-deploy.environment]
NODE_ENV = "branch"
